trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  vmImage: ubuntu-latest
  containerRegistryConnectionName: 'ACR connection'
  frontendDockerfile: '**/src/frontend/Dockerfile'
  backendDockerfile: '**/src/backend/Dockerfile'
  
stages:
  - stage: Build & Push images to ACR
    displayName: Build & Push images to ACR
    jobs:  
    - job: BuildFrontend
      displayName: Build & Push frontend
      pool:
        vmImage: $(vmImage)
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(containerRegistryConnectionName)
          repository: 'frontend'
          command: 'buildAndPush'
          Dockerfile: $(frontendDockerfile)
          tags: $(Build.BuildId)

    - job: BuildBackend
      displayName: Build & Push backend
      pool:
        vmImage: $(vmImage)
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: $(containerRegistryConnectionName)
            repository: 'backend'
            command: 'buildAndPush'
            Dockerfile: $(backendDockerfile)
            tags: $(Build.BuildId)
  