trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  vmImage: ubuntu-latest
  containerRegistryConnectionName: 'ACR connection'
  frontendDockerfile: '**/src/frontend/Dockerfile'
  backendDockerfile: '**/src/backend/Dockerfile'
  
stages:
  - stage: Build
    displayName: Build images
    jobs:  
    - job: BuildFrontend
      displayName: Build frontend
      pool:
        vmImage: $(vmImage)
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(containerRegistryConnectionName)
          repository: 'frontend'
          command: 'build'
          Dockerfile: $(frontendDockerfile)
          tags: $(Build.BuildId)

    - job: BuildBackend
      displayName: Build backend
      pool:
        vmImage: $(vmImage)
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: $(containerRegistryConnectionName)
            repository: 'backend'
            command: 'build'
            Dockerfile: $(backendDockerfile)
            tags: $(Build.BuildId)
  
  - stage: Push
    displayName: Push images to ACR
    jobs:  
    - job: PushFrontend
      displayName: Push frontend image to ACR
      pool:
        vmImage: $(vmImage)
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(containerRegistryConnectionName)
          repository: 'frontend'
          command: 'push'
          Dockerfile: $(frontendDockerfile)
          tags: $(Build.BuildId)
        
    - job: PushBackend
      displayName: Push backend image to ACR
      pool:
        vmImage: $(vmImage)
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: $(containerRegistryConnectionName)
          repository: 'backend'
          command: 'push'
          Dockerfile: $(backendDockerfile)
          tags: $(Build.BuildId)
