trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  acrConnection: 'ACR connection'
  
steps:
  - task: Docker@2
    displayName: Build and push frontend image to ACR
    inputs:
      containerRegistry: $(acrConnection)
      repository: 'frontend'
      command: 'buildAndPush'
      Dockerfile: '**/src/frontend/Dockerfile'
      tags: $(Build.BuildId)
  
  - task: Docker@2
    displayName: Build and push backend image to ACR
    inputs:
      containerRegistry: $(acrConnection)
      repository: 'backend'
      command: 'buildAndPush'
      Dockerfile: '**/src/backend/Dockerfile'
      tags: $(Build.BuildId)
